schemaVersion: 1
enabledWorkflows:
  - simulator
  - device
sessionDefaultsProfiles:
  sirius:
    projectPath: /Users/robertwaltham/Documents/iOS/DungeonsAndLlamas/DungeonsAndLlamas.xcodeproj
    scheme: DungeonsAndLlamas
    configuration: Debug
    deviceId: 5771124D-00F3-5E80-8696-403B3FD55716
    derivedDataPath: /private/tmp/DungeonsAndLlamasDerivedData-Sirius
    platform: iOS
activeSessionDefaultsProfile: sirius
